drop table visit;
drop table freeboard;
drop SEQUENCE freeboard_seq;
drop table freecomments;
drop SEQUENCE freecomments_seq;
drop table questionboard;
drop SEQUENCE questionboard_seq;
drop table questioncomments;
drop SEQUENCE questioncomments_seq;
drop table noticeboard;
drop SEQUENCE noticeboard_seq;
drop table noticecomments;
drop SEQUENCE noticecomments_seq;
drop table burger;
drop table set_menu;
drop table mc_morning;
drop table happy_meal;
drop table happy;
drop table snack_side;
drop table mc_cafe;
drop table beverage;
drop table desert;
drop table game;
drop table members;
drop sequence member_seq;
drop table study;
drop table supportboard;
drop sequence support_seq;
drop table coffee_coffee;
drop table coffee_latte;
drop table coffee_holly;
drop table coffee_tea;
drop table coffee_bakery;
drop table lotte_bugerset;
drop table lotte_chickenset;
drop table lotte_good;
drop table lotte_burger;
drop table lotte_chicken;
drop table lotte_desert;
drop table lotte_drink;
drop table pizza_seed;
drop table pizza_prm;
drop table pizza_cls;
drop table pizza_side;
drop table pizza_beverage;
drop table pizza_souce;



COMMIT;

select * from user_tables;
